server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  redis:
    host: 192.168.141.151
    port: 6379
    password: 1234
    cluster:
      nodes:
        -192.168.141.151:7001
        -192.168.141.151:7002
        -192.168.141.151:7003
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
        max-wait: 3000ms
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
canal:
  destination: heima # canal的集群名字，要与安装canal时设置的名称一致
  server: 192.168.141.151:11111 # canal服务地址
